# Generated by Django 4.0.2 on 2022-02-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_news_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, verbose_name='Опубликовано'),
        ),
    ]
